# Basic CI/CD Configuration File
project_language: "java-maven"
runUnitTests: true
runLintTests: true

tool_for_unit_testing:
  java: "junit"
tool_for_lint_testing:
  java: "checkstyle"

# Basic Notification Configuration
notifications:
  email:
    recipients: 
      - "smanprit022@gmail.com"
  # slack:
  #   channel: "#builds"

# Quality Gates (UNSTABLE vs FAILED)
quality_gates:
  lint:
    fail_on_error: false     # false = UNSTABLE, true = FAILED
    generate_report: true    # Generate detailed lint report
  unit_test:
    fail_on_error: false     # false = UNSTABLE, true = FAILED
    generate_report: true    # Generate detailed test report

# Report Configuration
reports:
  allure:
    enabled: true
    results_path: "allure-results"
    report_path: "allure-report"
  lint:
    enabled: true
    checkstyle_xml: "target/checkstyle-result.xml"

