# Basic CI/CD Configuration File
project_language: "java-maven"
runUnitTests: true
runLintTests: true

tool_for_unit_testing:
  java: "junit"
tool_for_lint_testing:
  java: "checkstyle"

# Basic Notification Configuration
notifications:
  email:
    recipients: 
      - "smanprit022@gmail.com"
  slack:
    channel: "#builds"

