project_language: "java-maven"
runUnitTests: true
runLintTests: true
tool_for_unit_testing:
  java: "junit"
tool_for_lint_testing:
  java: "checkstyle"
# Add notification settings to your config
notifications:
  slack:
    enabled: true
    channel: "#builds"
  email:
    enabled: true
    recipients: ["smanprit022@gmail.com"]
  

