# Basic CI/CD Configuration File
project_language: "java-maven"
runUnitTests: true
runLintTests: true

tool_for_unit_testing:
  python: "pytest"
tool_for_lint_testing:
  python: "pylint"

# Basic Notification Configuration
notifications:
  email:
    recipients: 
      - "smanprit022@gmail.com"
  slack:
    enabled: false           # Set to true when you get Slack access
    channel: "#builds"
